catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBookByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.AllLoanedBooksListView.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import uuid
from datetime import date


# Create your models here.
class Author(models.Model):
    """Model representing the author."""

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the model object."""
        return f'{self.last_name}, {self.first_name}'


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""

    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file.
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField('Genre', help_text='Select a genre for this book')
    # ManyToManyField used because genre can contain many books. Books can also cover many genres.
    # Genre class has already been defined so we can specify the object above.
    # language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)


    def __str__(self):
        """String for representing the Model object."""

        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""

        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across the whole library")
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200, blank=True)
    due_back = models.DateField('Due Date', null=True, blank=True)

    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1,
                              choices=LOAN_STATUS,
                              blank=True,
                              default='m',
                              help_text='Book availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"), )

    def __str__(self):
        """String for representing the Model object."""

        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Genre(models.Model):
    """Model representing a book's genre."""

    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Fiction, Non-Fiction, Fantasy, "
                                                      "Science Fiction, etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""

        return self.name


# class Language(models.Model):
#     """Model representing a language (e.g. English, Spanish, Japanese, etc.)"""
#     name = models.CharField(max_length=200, help_text="Enter the book's natural language (e.g. English, Spanish, Japanese, etc.")
#
#     def __str__(self):
#         return self.name

catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm
from .models import BookInstance
import datetime

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date. Renewal is in the past.'))

        # Check date is in range librarian is allowed to change (+4 weeks).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date. Renewal is more than 4 weeks ahead.'))

        # Return cleaned data
        return data

# This is the exact same as the RenewBookForm class above. Just an example of using ModelForm over ordinary Form
# class RenewBookModelForm(ModelForm):
#     def clean_due_back(self):
#         data = self.cleaned_data['due_back']
#
#         # Check date is not in the past.
#         if data < datetime.date.today():
#             raise ValidationError(_('Invalid date. Renewal is in the past.'))
#
#         # Check date is in range librarian is allowed to change (+4 weeks).
#         if data > datetime.date.today() + datetime.timedelta(weeks=4):
#             raise ValidationError(_('Invalid date. Renewal is more than 4 weeks ahead.'))
#
#         # Return cleaned data
#         return data
#
#     class Meta:
#         model = BookInstance
#         fields = ['due_back']
#         labels = {'due_back': _('Renewal Date'), }
#         help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).'), }

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import permission_required
import datetime

from .models import Book, Author, BookInstance, Genre
from .forms import RenewBookForm


# Create your views here.
def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()  # The 'all()' is implied by default

    num_genres = Genre.objects.all().count()
    num_of_books_with_word = Book.objects.filter(title__icontains="the").count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1


    # Render the HTML template index.html with the data in the context variable
    return render(request, 'catalog/index.html', context={'num_books': num_books,
                                                          'num_instances': num_instances,
                                                          'num_instances_available': num_instances_available,
                                                          'num_authors': num_authors,
                                                          'num_genres': num_genres,
                                                          'num_of_books_with_word': num_of_books_with_word,
                                                          'num_visits': num_visits}, )


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10


class BookDetailView(generic.DetailView):
    model = Book


class AuthListView(generic.ListView):
    model = Author
    paginate_by = 10


class AuthDetailView(generic.DetailView):
    model = Author


class LoanedBookByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""

    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class AllLoanedBooksListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    """Generic class-based view listing all books on loan. Only visible to users with can_mark_returned permission"""

    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian"""

    book_inst = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required( we write it to the model due_back field)
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed'))

    # if this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date, })

    return render(request, 'catalog/book_renew_librarian.html', {'form': form, 'bookinst': book_inst})


class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '05/01/2018', }

    permission_required = 'catalog.can_mark_returned'


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

    permission_required = 'catalog.can_mark_returned'


class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

    permission_required = 'catalog.can_mark_returned'


class BookCreate(PermissionRequiredMixin, CreateView):
    model = Book
    fields = '__all__'
    permission_required = 'catalog.can_mark_returned'


class BookUpdate(PermissionRequiredMixin, UpdateView):
    model = Book
    fields = '__all__'
    permission_required = 'catalog.can_mark_returned'


class BookDelete(PermissionRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('books')

    permission_required = 'catalog.can_mark_returned'

catalog/templates/catalog/author_confirm_delete.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
	<h1>Delete Author</h1>
	<p>Are you sure you want to delete the author: {{ author }}?</p>

	<form action="" method="post">
		{% csrf_token %}
		<input type="submit" action="" value="Yes, delete."/>
	</form>
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends 'catalog/base_generic.html' %}

{% block content %}

<h1>Author: {{ author }}</h1>

<p>{% if author.date_of_birth %}{{ author.date_of_birth }} -{% endif %} {% if author.date_of_death %}{{ author.date_of_death }}{% endif %}</p>

<div style="margin-left: 20px; margin-top: 20px;">
	<h4>Books</h4>
	<dl>
		{% for book in author.book_set.all %}
			<dt>
				<a href="{% url 'book-detail' book.pk %}">{{ book }}</a> ({{ book.bookinstance_set.all.count }})
			</dt>
			<dd>{{ book.summary }}</dd>
		{% endfor %}
	</dl>
</div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
<form action="" method="post">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<input type="submit" value="Submit"/>
</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
	<h1>Author List</h1>

	{% if author_list %}
	<ul>
		{% for author in author_list %}
		<li>
			<a href="{{ author.get_absolute_url }}">
				{{ author }} {% if author.date_of_birth %}({{ author.date_of_birth }} -{% endif %} {% if author.date_of_death %}{{ author.date_of_death }}){% endif %}
			</a>
		</li>
		{% endfor %}
	</ul>
	{% else %}
		<p>There are no authors available.</p>
	{% endif %}

{% endblock %}

catalog/templates/catalog/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    <title>Local Library</title>
    {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<!-- Add additional CSS in static file -->
	{% load static %}
{#<link rel="stylesheet" href="{% static 'css/styles.css' %}">#}
    <style type="text/css">
        .sidebar-nav {
            margin-top: 20px;
            padding: 0;
            list-style: none;
        }
    </style>
</head>
<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-2">
				{% block sidebar %}
					<ul class="sidebar-nav">
						<li><a href="{% url 'index' %}">Home</a></li>
						<li><a href="{% url 'books' %}">All Books</a></li>
						<li><a href="{% url 'authors' %}">All Authors</a></li>
					</ul>
					<ul class="sidebar-nav">
						{% if user.is_authenticated %}
							<li>User: {{ user.get_username }}</li>
							<li>
								<a href="{% url 'my-borrowed' %}">My Borrowed Books</a>
							</li>
							<li>
								<a href="{% url 'logout' %}?next={{ request.path }}">Logout</a>
							</li>
						{% else %}
							<li>
								<a href="{% url 'login' %}?next={{ request.path }}">Login</a>
							</li>
						{% endif %}
					</ul>

					{% if user.is_staff %}
					<hr/>
					<ul class="sidebar-nav">
						<li>Staff</li>
						{% if perms.catalog.can_mark_returned %}
						<li>
							<a href="{% url 'all-borrowed' %}">All Borrowed Books</a>
						</li>
						{% endif %}
					</ul>
					{% endif %}
				{% endblock %}
			</div>
			<div class="col-sm-10 ">
				{% block content %}

				{% endblock %}

				{% block pagination %}
					{% if is_paginated %}
						<div class="pagination">
							<span class="page-links">
								{% if page_obj.has_previous %}
									<a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
								{% endif %}
								<span class="page-current">
									Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
								</span>
								{% if page_obj.has_next %}
									<a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
								{% endif %}
							</span>
						</div>
					{% endif %}
				{% endblock %}
			</div>
		</div>
	</div>
</body>
</html>

catalog/templates/catalog/book_confirm_delete.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
	<h1>Delete Book</h1>
		<p>Are you sure you want to delete the book: {{ book }}?</p>

		<form action="" method="post">
			{% csrf_token %}
			<input type="submit" action="" value="Yes, delete."/>
		</form>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
	<h1>Title: {{ book.title }}</h1>

	<p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
	<p><strong>Summary:</strong> {{ book.summary }}</p>
	<p><strong>ISBN:</strong> {{ book.isbn }}</p>
	<p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

	<div style="margin-left: 20px; margin-top: 20px;">
		<h4>Copies</h4>

		{% for copy in book.bookinstance_set.all %}
		<hr>
		<p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
		{% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>{% endif %}
		<p><strong>Imprint:</strong> {{ copy.imprint }}</p>
		<p class="text-muted"><strong>ID:</strong> {{ copy.id }}</p>
		{% endfor %}
	</div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
<form action="" method="post">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<input type="submit" value="Submit"/>
</form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
	<h1>Book List</h1>

	{% if book_list %}
	<ul>
		{% for book in book_list %}
		<li>
			<a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
		</li>
		{% endfor %}
	</ul>
	{% else %}
		<p>There are no books in the library.</p>
	{% endif %}

{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "catalog/base_generic.html" %}

{% block content %}
	<h1>Renew: {{ bookinst.book.title }}</h1>
	<p>Borrower: {{ bookinst.borrower }}</p>
	<p {% if bookinst.is_overdue %} class="text-danger" {% endif %}>Due date: {{ bookinst.due_back }}</p>

	<form action="" method="post">
		{% csrf_token %}
		<table>
			{{ form }}
		</table>
		<input type="submit" value="Submit"/>
	</form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
	<h1>All Borrowed Books</h1>

	{% if bookinstance_list %}
	<ul>
		{% for bookinst in bookinstance_list %}
		<li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
			<a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a>
			({{ bookinst.due_back }}) {% if user.is_staff %}- {{ bookinst.borrower }}{% endif %}
			{% if perms.catalog.can_mark_returned %}-
			<a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>
			{% endif %}
		</li>
		{% endfor %}
	</ul>

	{% else %}
		<p>There are no books borrowed.</p>
	{% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'catalog/base_generic.html' %}

{% block content %}
	<h1>Borrowed Books</h1>

	{% if bookinstance_list %}
	<ul>
		{% for bookinst in bookinstance_list %}
		<li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
			<a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a>
			({{ bookinst.due_back }})
		</li>
		{% endfor %}
	</ul>

	{% else %}
		<p>There are no books borrowed.</p>
	{% endif %}
{% endblock %}

catalog/templates/catalog/index.html
{% extends "catalog/base_generic.html" %}

{% block title %}
<title>Home</title>
{% endblock %}

{% block content %}
<h1>Library Home</h1>

    <p>Welcome to <em>Austin's Library</em>, a basic Library website created with Django.</p>

<h2>Library Content</h2>

    <p>The library has the following record counts:</p>
    <ul>
        <li><strong>Books:</strong> {{ num_books }}</li>
        <li><strong>Copies:</strong> {{ num_instances }}</li>
        <li><strong>Copies Available:</strong> {{ num_instances_available }}</li>
        <li><strong>Authors:</strong> {{ num_authors }}</li>
		<li><strong>Genres:</strong> {{ num_genres }}</li>

{#		<li><strong>Titles Containing Word "The":</strong> {{ num_of_books_with_word }}</li>#}

    </ul>

	<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
{% endblock %}